#server
server:
  port: 8888
  context-path: /api


spring:
  datasource:
#    url: jdbc:mysql://rm-uf6mmio3c34252299go.mysql.rds.aliyuncs.com/xbtest?serverTimezone=Asia/Shanghai
#    username: xbtest
#    password: Xbtest123456
    url: jdbc:mysql://139.196.12.156:3306/xiaoBlog?serverTimezone=Asia/Shanghai
    username: xsyroot
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver