#server
server:
  port: 8888
  context-path: /api


spring:
  datasource:
#    url: jdbc:mysql://rm-uf6mmio3c34252299go.mysql.rds.aliyuncs.com/xbtest?serverTimezone=Asia/Shanghai
#    username: xbtest
#    password: Xbtest123456
    url: jdbc:mysql://47.94.34.191:3306/newDemo?serverTimezone=Asia/Shanghai
    username: root
    password: root01
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

redis:
  database: 4
  host: 47.94.34.191
  port: 6379
  password: 123456
  jedis:
      pool:
          max-active: -1
          max-wait: 5s
          max-idle: -1
          min-idle: 50
      timeout: 5s
      servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
      session:
        store-type: redis
        timeout: 1800s
